GET http://localhost:3003/api/blogs/

###
POST http://localhost:3003/api/blogs/ HTTP/1.1
content-type: application/json

{
    "title": "Test Blog",
    "author": "John Smith",
    "url": "http://www.testblog.com",
    "likes": 0
}